# https://taskfile.dev

version: "3"

vars:
  VCPKG: "{{.USER_WORKING_DIR}}/Submodules/vcpkg"
  VCPKG_SOURCE_URL: https://github.com/microsoft/vcpkg
  BUILD_DIR: "{{.USER_WORKING_DIR}}/.build"
  SOURCE_DIR: "{{.USER_WORKING_DIR}}"
  PROJECT_DIR: "{{.USER_WORKING_DIR}}"

tasks:
  default:
    cmds:
      - cmd: 'cmake -B "{{.BUILD_DIR}}" -S "{{.SOURCE_DIR}}" "-DCMAKE_TOOLCHAIN_FILE={{.VCPKG}}/scripts/buildsystems/vcpkg.cmake"'
      - cmd: 'cmake --build "{{.BUILD_DIR}}"'
    silent: false

  init:
    cmds:
      - git submodule deinit -f --all
      - cmd: git -C "{{.PROJECT_DIR}}" submodule add -b master --force -- "{{.VCPKG_SOURCE_URL}}" "Submodules/vcpkg"
        ignore_error: true
      - cmd: git -C "{{.PROJECT_DIR}}" submodule add -b master --force -- "https://github.com/xmichelo/XMiLib" "Submodules/XMiLib"
        ignore_error: true
      - cmd: git -C "{{.PROJECT_DIR}}" submodule add -b main --force -- "https://github.com/muan/emojilib" "Submodules/emojilib"
        ignore_error: true
      - git -C "{{.PROJECT_DIR}}" submodule update --init
      - git -C "{{.PROJECT_DIR}}" submodule update --recursive --checkout --remote

      # https://github.com/microsoft/vcpkg?tab=readme-ov-file#quick-start-windows
      - cmd: '"{{.VCPKG}}" integrate install'
        ignore_error: true
