# https://taskfile.dev

version: "3"

vars:
  VCPKG: "{{.USER_WORKING_DIR}}/Submodules/vcpkg"
  VCPKG_BOOTSTRAP: "{{.USER_WORKING_DIR}}/Submodules/vcpkg/bootstrap-vcpkg.bat"
  VCPKG_SOURCE_URL: https://github.com/microsoft/vcpkg
  BUILD_DIR: "{{.USER_WORKING_DIR}}/.build"
  SOURCE_DIR: "{{.USER_WORKING_DIR}}"
  PROJECT_DIR: "{{.USER_WORKING_DIR}}"
  RM: '{{if eq .OS "Windows_NT"}}cmd /d /c rmdir /q /s{{else}}rm -rf{{end}}'
  PACKAGE_MANAGER: '{{if eq .OS "Windows_NT"}}scoop{{else}}apt{{end}}'
  INSTALL: "{{.PACKAGE_MANAGER}} install"
  UPDATE: "{{.PACKAGE_MANAGER}} update"
  PKG_QT_CREATOR: '{{if eq .OS "Windows_NT"}}extras/qt-creator{{else}}qt-creator{{end}}'

env:
  VCPKG_DISABLE_METRICS: 1

tasks:
  default:
    deps: [init]
    cmds:
      - cmd: 'cmake -B "{{.BUILD_DIR}}" -S "{{.SOURCE_DIR}}" "-DCMAKE_TOOLCHAIN_FILE={{.VCPKG}}/scripts/buildsystems/vcpkg.cmake"'
      - cmd: 'cmake --build "{{.BUILD_DIR}}"'
    silent: false

  install:
    cmds:
      - "{{.INSTALL}} {{.PKG_QT_CREATOR}}"
      - "{{.UPDATE}} {{.PKG_QT_CREATOR}}"
      - task: init

  init:
    cmds:
      - task: init-git
      - task: init-vcpkg

  init-git:
    cmds:
      - cmd: git -C "{{.PROJECT_DIR}}" submodule init
      - cmd: git -C "{{.PROJECT_DIR}}" submodule update --init --recursive

  init-git-submodules:
    cmds:
      - cmd: git rm --cached "{{.PROJECT_DIR}}/vcpkg"
        ignore_error: true
        dir: "{{.PROJECT_DIR}}"
      - task: clean
      - cmd: git submodule deinit -f --all
      - cmd: git -C "{{.PROJECT_DIR}}" submodule add -b master --force -- "{{.VCPKG_SOURCE_URL}}" "Submodules/vcpkg"
        ignore_error: true
      - cmd: git -C "{{.PROJECT_DIR}}" submodule add -b master --force -- "https://github.com/xmichelo/XMiLib" "Submodules/XMiLib"
        ignore_error: true
      - cmd: git -C "{{.PROJECT_DIR}}" submodule add -b main --force -- "https://github.com/muan/emojilib" "Submodules/emojilib"
        ignore_error: true
      - git -C "{{.PROJECT_DIR}}" submodule update --init
      - git -C "{{.PROJECT_DIR}}" submodule update --recursive --checkout --remote

  init-vcpkg:
    cmds:
      # https://github.com/microsoft/vcpkg?tab=readme-ov-file#quick-start-windows
      - cmd: '{{if eq .OS "Windows_NT"}}cmd /d /c if exist "{{fromSlash .VCPKG_BOOTSTRAP}}" call "{{fromSlash .VCPKG_BOOTSTRAP}}" -disableMetrics{{end}}'
        ignore_error: true
    env:
      VCPKG_DISABLE_METRICS: 1

  clean:
    deps:
      - clean-git
      - clean-docs
      - clean-downloads
      - clean-packages
      - clean-ports
      - clean-versions
      - clean-toolsrc
      - clean-triplets
      - clean-scripts
      - clean-buildtrees

  clean-git:
    cmds:
      - task: remove-cache
        vars: { TARGET: "{{.PROJECT_DIR}}/vcpkg/.git" }

  clean-docs:
    cmds:
      - task: remove-cache
        vars: { TARGET: "{{.PROJECT_DIR}}/vcpkg/docs" }

  clean-downloads:
    cmds:
      - task: remove-cache
        vars: { TARGET: "{{.PROJECT_DIR}}/vcpkg/downloads" }

  clean-packages:
    cmds:
      - task: remove-cache
        vars: { TARGET: "{{.PROJECT_DIR}}/vcpkg/packages" }

  clean-ports:
    cmds:
      - task: remove-cache
        vars: { TARGET: "{{.PROJECT_DIR}}/vcpkg/ports" }

  clean-versions:
    cmds:
      - task: remove-cache
        vars: { TARGET: "{{.PROJECT_DIR}}/vcpkg/versions" }

  clean-toolsrc:
    cmds:
      - task: remove-cache
        vars: { TARGET: "{{.PROJECT_DIR}}/vcpkg/toolsrc" }

  clean-triplets:
    cmds:
      - task: remove-cache
        vars: { TARGET: "{{.PROJECT_DIR}}/vcpkg/triplets" }

  clean-scripts:
    cmds:
      - task: remove-cache
        vars: { TARGET: "{{.PROJECT_DIR}}/vcpkg/scripts" }

  clean-buildtrees:
    cmds:
      - task: remove-cache
        vars: { TARGET: "{{.PROJECT_DIR}}/vcpkg/buildtrees" }

  remove-cache:
    deps: []
    internal: true
    vars:
      TARGET: '{{default ".temp" .TARGET}}'
    cmds:
      - cmd: '{{if eq .OS "Windows_NT"}}cmd /d /c if exist "{{fromSlash .TARGET}}" rmdir /q /s "{{fromSlash .TARGET}}"{{end}}'
        timeout: 5s
      - cmd: '{{if eq .OS "Windows_NT"}}cmd /d /c if exist "{{fromSlash .TARGET}}" del "{{fromSlash .TARGET}}"{{end}}'
        timeout: 5s
